language: node_js

node_js:
  - '6'

sudo: required

services:
  - docker

matrix:
  include:
  - env:
    - BUILD_TASK=test
    - TAG=3.0.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.1.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.2.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.3.0-contrib
  - env:
    - BUILD_TASK=cover
    - TAG=3.4.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.4.0-contrib-world
  - env:
    - BUILD_TASK=test
    - TAG=3.4.1-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.4.2-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.4.3
  - env:
    - BUILD_TASK=test
    - TAG=3.4.3-contrib

before_install:
  - chmod +x ./ci/$BUILD_TASK/$BUILD_TASK.sh

install: travis_wait 30 docker pull justadudewhohacks/opencv4nodejs-ci:$TAG

script:
  - cd ./ci/$BUILD_TASK
  - npm run $BUILD_TASK $TAG

after_success:
  - if [ $BUILD_TASK = 'cover' ]; then
    npm install;
    npm run codecov -- -t $CODECOV_TOKEN;
    fi