# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

platform:
  - x64

image:
  - Visual Studio 2015

clone_folder: c:\projects\opencv4nodejs

init:
  - git config --global core.autocrlf true

# cache:
 # - c:\tools\opencv

# what combinations to test
environment:
  matrix:
    # node 9
    - nodejs_version: 9
      PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      opencv_version: 3.3.0
      # use self build
      OPENCV4NODEJS_DISABLE_AUTOBUILD: 1
    # node 6
    - nodejs_version: 6
      PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      opencv_version: 3.3.0
      # use self build
      OPENCV4NODEJS_DISABLE_AUTOBUILD: 1


install:
  - cmd: choco install OpenCV -y -version %OPENCV_VERSION%
  - IF EXIST c:\tools\opencv* CD c:\tools\opencv*
  - SET OPENCV_INCLUDE_DIR=%CD%\build\include
  - SET OPENCV_LIB_DIR=%CD%\build\x64\vc14\lib
  - SET OPENCV_BIN_DIR=%CD%\build\x64\vc14\bin
  - SET PATH=%PATH%;%OPENCV_BIN_DIR%;

  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm install -g node-gyp
  - cd c:\projects\opencv4nodejs
  - npm install

build: off

test_script:
  - node --version
  - cmd: cd c:\projects\opencv4nodejs\test
  - npm install
  - npm run test-appveyor
  - npm run test-externalMemTracking